version: "3.8"
services: 
  db:
    build: ./db/
    ports:
      - 5432:5432
    volumes:
        - /var/lib/postgres
    environment:
        POSTGRES_DB: rates
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
       
  app :
    build: ./rates/
    ports:
      - 3000:3000
    depends_on:
      - db  